default:
    just --list

all: build test
all-release: build-release test-release

[group('building')]
@build:
    cargo build

[group('building')]
@build-release:
    cargo build --release --verbose

[group('building')]
@check:
    cargo check

[group('testing')]
@test:
    cargo test --workspace --all-features -- --quiet

[group('testing')]
@test-release:
    cargo test --workspace --all-features --release --verbose

[group('house-keeping')]
@fmt:
    cargo +nightly fmt -- --check

[group('house-keeping')]
@clippy:
    cargo clippy --workspace --all-features --all-targets -- -D warnings

[group('house-keeping')]
@unused-deps:
    command -v cargo-udeps >/dev/null || (echo "cargo-udeps not installed" && exit 1)
    cargo +nightly udeps

[group('house-keeping')]
@typos:
    typos

# ==================================== #
#     RELEASE WORKFLOW. DO NOT USE     #
# ==================================== #

new_version := "$(convco version --bump)"

[group('release')]
release:
    git cliff -t "{{new_version}}" > CHANGELOG.md
    cargo check
    git checkout -b milky-release-v"{{new_version}}"
    git add -A
    git commit -m "chore(release): prepare for release milky v{{new_version}}"
    git push --set-upstream origin milky-release-v"{{new_version}}"
    @echo "waiting 10 seconds so github catches up"
    sleep 10
    gh pr create --draft --title "chore: release milky v{{new_version}}" --body "This is an CI auto-generated PR" --reviewer wllfaria
    echo "generated release pull request successfully"

[group('release')]
gh-release:
    git tag -d "v{{new_version}}" || echo "tag not found, creating"
    git tag -a "v{{new_version}}" -m "auto generated by the justfile for milky v$(convco version)"
    just cross
    mkdir -p ./target/"release-notes-$(convco version)"
    git cliff -t "v$(convco version)" --current > ./target/"release-notes-$(convco version)/RELEASE.md"
    just checksum >> ./target/"release-notes-$(convco version)/RELEASE.md"
    git push origin "v{{new_version}}"
    gh release create "v$(convco version)" --target "$(git rev-parse HEAD)" --title "milky v$(convco version)" -d -F ./target/"release-notes-$(convco version)/RELEASE.md" ./target/"bin-$(convco version)"/*

[group('binaries')]
checksum:
    @echo "# Checksums"
    @echo "## sha256sum"
    @echo '```'
    @sha256sum ./target/"bin-$(convco version)"/*
    @echo '```'
    @echo "## md5sum"
    @echo '```'
    @md5sum ./target/"bin-$(convco version)"/*
    @echo '```'
    @echo "## blake3sum"
    @echo '```'
    @b3sum ./target/"bin-$(convco version)"/*
    @echo '```'

[group('binaries')]
tar BINARY TARGET:
    tar czvf ./target/"bin-$(convco version)"/{{BINARY}}_{{TARGET}}.tar.gz -C ./target/{{TARGET}}/release/ ./{{BINARY}}

[group('binaries')]
zip BINARY TARGET:
    zip -j ./target/"bin-$(convco version)"/{{BINARY}}_{{TARGET}}.zip ./target/{{TARGET}}/release/{{BINARY}}

[group('binaries')]
tar_static BINARY TARGET:
    tar czvf ./target/"bin-$(convco version)"/{{BINARY}}_{{TARGET}}_static.tar.gz -C ./target/{{TARGET}}/release/ ./{{BINARY}}

[group('binaries')]
zip_static BINARY TARGET:
    zip -j ./target/"bin-$(convco version)"/{{BINARY}}_{{TARGET}}_static.zip ./target/{{TARGET}}/release/{{BINARY}}

[group('binaries')]
binary BINARY TARGET:
    rustup target add {{TARGET}}
    cross build --release --target {{TARGET}}
    just tar {{BINARY}} {{TARGET}}
    just zip {{BINARY}} {{TARGET}}

[group('binaries')]
binary_static BINARY TARGET:
    rustup target add {{TARGET}}
    RUSTFLAGS='-C target-feature=+crt-static' cross build --release --target {{TARGET}}
    just tar_static {{BINARY}} {{TARGET}}
    just zip_static {{BINARY}} {{TARGET}}

[group('binaries')]
binary_no_libgit BINARY TARGET:
    rustup target add {{TARGET}}
    cross build --no-default-features --release --target {{TARGET}}
    just tar {{BINARY}} {{TARGET}}
    just zip {{BINARY}} {{TARGET}}

[group('binaries')]
binary_static_no_libgit BINARY TARGET:
    rustup target add {{TARGET}}
    RUSTFLAGS='-C target-feature=+crt-static' cross build --no-default-features --release --target {{TARGET}}
    just tar_static {{BINARY}} {{TARGET}}
    just zip_static {{BINARY}} {{TARGET}}

[group('binaries')]
cross:
    # Setup Output Directory
    mkdir -p ./target/"bin-$(convco version)"

    rustup toolchain install stable

    ## Linux
    ### x86
    just binary milky x86_64-unknown-linux-gnu
    just binary_static milky x86_64-unknown-linux-gnu
    just binary milky x86_64-unknown-linux-musl
    just binary_static milky x86_64-unknown-linux-musl

    ### aarch
    just binary_no_libgit milky aarch64-unknown-linux-gnu
    just binary_static milky aarch64-unknown-linux-gnu

    ### arm
    just binary_no_libgit milky arm-unknown-linux-gnueabihf
    just binary_static milky arm-unknown-linux-gnueabihf

    ## Windows
    ### x86
    just binary milky.exe x86_64-pc-windows-gnu
    just binary_static milky.exe x86_64-pc-windows-gnu
