[package]
name = "milky_fen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
milky_bitboard.workspace = true

thiserror.workspace = true

[dev-dependencies]
insta = "1.43.1"
