[package]
name = "milky_protocols"
version.workspace = true
edition.workspace = true

[dependencies]
milky_chess.workspace = true
milky_bitboard.workspace = true
milky_fen.workspace = true

thiserror.workspace = true
