[package]
name = "milky_chess"
version.workspace = true
edition.workspace = true

[dependencies]
milky_bitboard.workspace = true
milky_fen.workspace = true

bitflags = "2.9.0"

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "perft"
harness = false

[[bench]]
name = "search"
harness = false
