[project]
name = "milky_scripts"
version = "0.1.0"
description = "Scripts for milky engine"
readme = "../README.md"
requires-python = ">=3.12"
dependencies = [
    "ax-platform>=1.0.0",
    "numpy>=2.2.6",
    "python-chess>=1.999",
]

[tool.pyright]
reportMissingTypeStubs = false
