[package]
name = "milky_cli"
version.workspace = true
edition.workspace = true

[dependencies]
milky_chess.workspace = true
milky_uci.workspace = true
milky_fen.workspace = true

[[bin]]
name = "milky"
path = "./src/main.rs"
